prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun

- .eslintrc.json
- .husky/pre-commit
- package-lock.json
- package.json
#3 이슈에 대한 작업을 수행했습니다.
- husky로 pre-commit 규칙을 작성했습니다. lint-staged를 활용하여 git staging area에 올라온 작업만 검사하도록 설정했습니다.
- 커밋시 eslint, prettier 규칙에 어긋난 것들을 캐치하고, 자체적으로 eslint가 수정해줄 수 있는 것은 수정한 뒤 커밋하도록 설정했습니다. 만약, 자동으로 수정할 수 없는 규칙의 경우에는 커밋이 막히고 에러가 발생합니다.
- 사용하지 않는 변수가 존재하면 error가 발생하는 `@typescript-eslint/no-unused-vars` 룰이 너무 엄격하다고 생각하여 `error` 가 아니라 `warn` 을 보여주게끔 했습니다.
```sh
1. npm install husky --save-dev
2. npx husky install
3. package.json 에 "prepare": "husky install" 스크립트 추가
4. npx husky add .husky/pre-commit "npx lint-staged"
5. git add .husky/pre-commit
6. npm install --save-dev lint-staged
7. package.json 에 내용 추가
"lint-staged": {
"*.{cjs,js,jsx,ts,tsx}": [
"eslint --fix",
"prettier --write"
]
}
```
> husky, lint-staged 패키지 설정

- src/App.tsx
- src/pages/Main/index.tsx
- src/pages/Mainpage/index.tsx
- src/pages/Newpost/index.tsx
- src/pages/Post/index.tsx
- src/pages/Profile/index.tsx
- src/pages/Signin/index.tsx
- src/pages/Signup/index.tsx
- src/routes/index.tsx
> basic Route 설정

- src/main.css
- src/main.tsx
> Color 코드 상수화

- src/pages/Signup/index.tsx
- src/theme/index.tsx
- close #37
Button에 자주 사용되는 컬러 스타일을 지정했어요.
Button의 colorSchema 속성에 "primary" 를 전달하면 적용이 돼요.
> Primary 테마 속성 지정

- src/components/header/components/Button/index.tsx
- src/components/header/index.tsx
- src/pages/Main/index.tsx
- close #16 
- header UI 변경
- 로그인 전/후 UI 변경 코드 추가
각 페이지에서 Header 컴포넌트를 사용할 때 props로 useId를 전달해줘야 하는 형식으로 작성했습니다.
> feat: header 로그인 전/후 UI 변경 구현

- src/App.tsx
- src/apis/queries/useSearchUserQuery.ts
- src/components/header/components/Input/index.tsx
- src/components/header/index.tsx
- src/pages/Search/components/UserCard/index.tsx
- src/pages/Search/index.tsx
- src/theme/index.tsx
- close #63
- close #64
- body에 bgColor 통일
- 검색 페이지 UI 구현
- 헤더에서 사용자 검색 시 해당 이름의 사용자가 출력되도록 api 구현
- 검색 결과 페이지로 이동시 Input 초기화를 위해 react-hook-form의 reset함수 사용
- UserCard에 실제 서버 data 연결
- 검색어를 입력해서 onSubmit 핸들러 발생시 useQuery 호출하도록 refetch 사용
오프라인에서 JSON형태로 오지 않는 초기 생성 데이터들을 어떻게 처리할지 논의해봐야합니다.
-> 강사님께 서버 데이터 초기화 요청하기 or 예외처리 만들기
> feat: 검색 페이지 구현

- src/components/Modal/index.tsx
- src/pages/Post/components/CommentListModal/AccordionItems/index.tsx
- src/pages/Post/components/CommentListModal/index.tsx
- src/pages/Post/index.tsx
- close #76 
- 한눈에 보기 모달 구현
- 리스트 보기 버튼 누르면 볼 수 있습니다.
- 실제 데이터는 추후에 연결 예정
> feat: 한눈에 보기 모달 구현

- src/pages/Newpost/index.tsx
- src/pages/Profile/index.tsx
- close #83
- 이미지 경로 문제로 빌드가 안되던 현상을 해결했어요
> hotfix: 이미지 import 경로 수정

- src/apis/instance.ts
- src/apis/mutations/useGenerateSlackLinkMutation.ts
- src/constants/slack.ts
- src/types/index.ts
- close #85
- 슬랙 서버와 통신하는 slackInstance 인스턴스를 만들었어요.
- SlackWorkspace의 타입을 작성했어요.
- 슬랙 서버에 인증 링크를 생성하도록 요청하는 useGenerateSlackLinkMutation.ts 훅을 만들었어요.
```tsx
const { mutate } = useGenerateSlackLinkMutation();
const handleClick = async () => {
mutate({ slackId: 사용자 슬랙 ID, slackWorkspace: 'Frontend' });
};
```
> 슬랙 서버와 통신하는 인스턴스 생성

- src/apis/mutations/useGenerateSlackLinkMutation.ts
- src/apis/mutations/useSlackMessageMutation.ts
- close #92
- 예전에 PR으로 올렸던 슬랙 인증 링크 관련한 훅에서 사용하는 mutationFn의 이름을 postSlackVerification 로 바꿨어요.
- 코멘트 내용을 DM으로 발송하는 useSlackMessageMutation 훅을 만들었어요.
- 게시글의 _id와, 코멘트의 _id를 담아서 보내야 해요.
- 슬랙 서버에서 해당 게시글 정보를 조회하는데, 그 게시글에서 해당 코멘트가 존재한다면 게시글의 작성자에게 코멘트의 내용이 슬랙 DM으로 발송 돼요.
게시글의 ID와, 코멘트의 ID를 파라미터로 전달해줘야 하는데요,
이 정보는 코멘트 작성 API인 `POST /comments/create` 요청의 결과로부터 유추할 수 있어요.
그래서 코멘트 작성 기능 API의 `onSuccess` 이후에 추가적으로 슬랙 DM을 발송하는 API도 호출하는 작업이 필요해 보여요.
```tsx
const { mutate: slackMessage } = useSlackMessageMutation();
const handleClick = () => {
slackMessage({
postId: '6507fd06b7d44e1cacaf2311',
commentId: '65080b3cb7d44e1cacaf2687'
});
};
```
여기에서 `_id` 가 commentId 이고, `post` 가 postId 예요.
```json
{
"_id": "65081283b7d44e1cacaf285b",
"comment": …
```
> 코멘트 내용을 DM으로 발송하는 훅 작성

- src/apis/utils/parseComment.ts
- src/apis/utils/parsePost.ts
- src/apis/utils/parseUser.ts
- close #94 
- 데이터 파싱 유틸 함수를 리팩토링했어요. (null 데이터 파싱 관련한 문제 해결)
> refactor: 데이터 파싱 유틸 함수 리팩토링

- src/apis/queries/usePostDetailQuery.ts
- src/apis/utils/parseComment.ts
- src/pages/Post/components/CommentBoard.tsx
- src/pages/Post/index.tsx
- src/types/index.ts
- close #108 
- 비 로그인 접근 시 로그인 페이지로 연결
- 없는 포스트 id 일 경우 404 페이지로 연결
- 포스트 작성자 || 댓글 작성자 인 경우만 댓글 볼 수 있도록 설정
- 방문자가 댓글 작성 가능 범위 쉽게 볼 수 있도록 스타일
> feat: 포스트 상세 페이지 리다이렉션 및 댓글 권한 설정

- src/apis/queries/useSlackTokenCheckQuery.ts
- src/apis/queryClient.ts
- src/apis/queryKeys.ts
- src/main.tsx
- close #115 
- useSlackTokenCheckQuery 훅이 임시로 가지고 있는 데이터를 ['auth'] 로 옮기고, 임시 데이터는 삭제하는 로직을 작성했어요.
- 쿼리키가 받는 id 파라미터의 이름을 더 명시적으로 적어봤어요.
- 슬랙 서버에 API 요청해서 받은 사용자 정보와 액세스 토큰을 임시 보관할 `queryKey.slack.token()` 을 작성했어요.
- 쿼리 데이터를 바로 지우면 로딩 처리와 관련한 에러가 발생해서 setTimeout으로 한 타이밍을 늦췄는데, 더 좋은 해결책이 있을지는 고민돼요.
> refactor: useSlackTokenCheckQuery 리팩토링

- src/apis/queries/useSearchUserQuery.ts
- src/pages/Search/index.tsx
- close #121 
기존에 파싱 전 데이터로 뿌려주던 값들을 파싱을 거쳐서 올바른 데이터로 출력되도록 수정했습니다!
> hotfix: search 페이지- parsing한 데이터로 출력하도록 수정

- src/apis/utils/parseComment.ts
- src/apis/utils/parsePost.ts
- src/apis/utils/parseUser.ts
- src/components/header/index.tsx
- src/pages/Profile/index.tsx
- close #124 
- profile 페이지 suspense 에러 임시해결 
- console.error() 주석처리
> hotfix: profile 페이지 suspense 에러 임시해결 + 주석처리

- src/hooks/useIsNotLoggedIn.ts
- src/pages/ChangePassword/index.tsx
- close #127 
슬슬 각 페이지에서 로그인 상태가 아닌 경우에 다른 페이지로 리다이렉션 해야 하는 로직을 작성할 일이 많다고 생각해서 로그인되지 않은 상태를 검사하는 간단한 `useIsNotLoggedIn.ts` 훅을 작성했어요.
각 컴포넌트에서 `isNotLoggedIn` 플래그 변수가 true이면 리다이렉션시키는 `Navigate` 컴포넌트를 반환하면 돼요.
```tsx
import { Navigate } from 'react-router-dom';
import useIsNotLoggedIn from '@/hooks/useIsNotLoggedIn';
const Page = () => {
const { isNotLoggedIn } = useIsNotLoggedIn();
if (isNotLoggedIn) return <Navigate to="/signin" />; {/* 비로그인 상태에 redirect할 페이지 */}
return (
<div>
하하 로그인 된 상태에서 보여줄 페이지 내용...
</div>
)
}
```
간단한 훅이라 만들까 말까 고민 되었는데 사용하기에 별로 유용하지 않은 것 같으면 머지 하지 않아도 됩니다~~
비로그인 상태에 리다이렉션 해야 하는 로직에 사용하시기 편하실지 궁금해요 😊
> feature: 비로그인 상태를 검사하는 useIsNotLoggedIn 훅 작성

- .husky/pre-commit
- .husky/pre-push
- package-lock.json
- package.json
- close #123 
윈도우 환경에서 세팅했던 husky가 특정 리눅스 환경에서 잘 작동하지 않던 문제를 해결했어요.
`(chmod ug+x .husky/*)`
> hotfix: husky가 특정 리눅스 환경에서 제대로 작동하지 않는 현상 해결

- src/apis/mutations/useProfileImageMutation.ts
- src/apis/queries/useSearchUserQuery.ts
- src/components/header/components/Menu/index.tsx
- src/components/header/index.tsx
- close #140 
- 
- 사용자 검색 input width 줄였습니다.
- 사용자 이름을 입력하지 않으면 폼 제출이 안되도록 막았습니다. 검색 아이콘을 눌러도 동작하지 않습니다.
- user, username을 검색하면 모든 유저의 데이터가 검색되어 나오는 것을 필터를 통해 막았습니다.(원인은 저희가 json을 직렬화해서 서버에 보낼때 key값이 username이기 때문)
- 프로필 이미지를 변경했을때 헤더의 프로필 이미지도 같이 실시간으로 변경되게 api를 수정했습니다.(단, 이미지 로딩 관계로 1~3초 소요)
> hotfix: header 검색 버그 수정 및 스타일 수정

- packages/web/src/components/header/index.tsx
- packages/web/src/pages/Newpost/index.tsx
- packages/web/src/pages/Search/components/UserCard/index.tsx
- packages/web/src/pages/Search/index.tsx
- close #169 
- tip ui 추가 구현
혹시 몰라서 미리 구현해놨습니다!! 슬랙에 여쭤봤는데 다들 괜찮으시다면 approve 받은 후 merge 하도록 하겠습니다.
> feat: 머쓱이 생성 페이지 tip ui 추가 구현

- packages/web/src/pages/Setting/Slack/index.tsx
- close #173 
인증하기 버튼 클릭시 버튼 비활성화 + 로딩 구현
> hotfix: 인증하기 버튼 로딩 + 클릭 시 비활성화 추가

- packages/web/src/pages/ChangePassword/index.tsx
- packages/web/src/pages/Signin/index.tsx
- packages/web/src/pages/Signup/index.tsx
- close #165 
- mutate 발생시 요청 결과가 오기 전까지 버튼을 disabled 처리 했어요.
> feat: 회원가입, 로그인, 비밀번호 변경 페이지 버튼 로딩 처리

- packages/web/src/apis/queries/useAuthCheckQuery.ts
- close #177 
무효한 로그인 토큰이면 스토리지에서 제거
> hotfix: 무효한 로그인 토큰이면 스토리지에서 제거

- packages/web/src/pages/Post/components/AnnouncementText.tsx
- packages/web/src/pages/Post/components/CommentInfoModal/index.tsx
- packages/web/src/pages/Post/components/CommentListModal/index.tsx
- packages/web/src/pages/Post/components/CommentWriteModal/index.tsx
- packages/web/src/pages/Post/components/PostDeleteModal/index.tsx
- packages/web/src/pages/Post/index.tsx
- close #191 
- 포스트 페이지 삭제 및 링크 버튼 모바일에서 텍스트와 겹침 수정
- 모달 모바일에서 마진 추가
- 삭제 모달 버튼 모바일 대응
> design: 일부 디자인 모바일 수정

- packages/web/src/pages/Profile/components/ProfileBar.tsx
> Hotfix: 프로필 버그 수정

- .github/ISSUE_TEMPLATE/🛠️-refactor.md
- close #199 
- 리팩토링 전용 이슈 템플릿 추가
> docs: refactor 템플릿 작성

- packages/web/src/components/WhiteCard/index.tsx
- packages/web/src/pages/Signin/index.tsx
- packages/web/src/pages/Signup/templates/LinkTemplate.tsx
- close #198 
- 회원가입, 로그인, 비밀번호 변경 페이지에서 반응형에 따른 padding 동작이 되지 않고 있던 문제를 해결했어요.
- 이전에 chakra-ui의 breakpoints 설정을 확장한 적이 있는데, 배열 형태로 스타일을 줬었다보니 적용되지 않는 문제였어요.
> Hotfix: WhiteCard, LinkTemplate 반응형 동작

- .github/workflows/react-deploy.yml
- packages/web/src/apis/instance.ts
- close #210 
- main 브랜치에 작업물이 올라오면 자동으로 배포하는 스크립트 작성
배포 URL: https://www.musseuk-letter.site/
> feature: 리액트 앱 CI 스크립트 작성

- .github/workflows/build-test.yml
- close #218 
- 빌드가 안되는 작업물이 통합 브랜치에 올라오지 않도록 PR 작성시 빌드를 수행하는 워크플로 작성
> chore: build-test 워크플로 추가
